# Baseline evaluation — FinVerify

This notebook runs a small, open-weights HuggingFace model (**Qwen2.5-3B-Instruct**) as the *baseline* financial advisor. It samples **5 questions from each of the three dataset subsets** (`standard_questions`, `open_ended_hard`, `reddit_questions`) and grades the answers with three signals:

1. **Multiple-choice accuracy** — exact letter match (only applies to MC items).
2. **Embedding similarity** — cosine similarity between the model answer and the reference `correct_answer`, using `BAAI/bge-small-en-v1.5`.
3. **LLM-as-judge rubric** — Claude scores the answer on `factuality`, `completeness`, and `advice_quality` (1–5 each).

Why a small open-weights baseline? The RAG notebook will use a frontier API model (Claude). Comparing Qwen-3B (no retrieval) against Claude + RAG would confound *retrieval gains* with *model-size gains*. The cleanest comparison is to also run **Claude with no retrieval** as a second baseline — we add that optionally at the bottom.

## 1. Setup

Install dependencies (uncomment the `%pip install` line on first run). Requires Python 3.10+.

The `ANTHROPIC_API_KEY` environment variable must be set for the LLM-judge step. Put it in your shell or a `.env` file; the notebook will skip the judge if it's missing and just show embedding-similarity scores.

In [1]:
import os, sys, json, time, platform, subprocess
from pathlib import Path

REPO_URL = "https://github.com/niksharma99/COMS6156FinalProject.git"
REPO_NAME = "COMS6156FinalProject"
# TODO: switch to "main" once the eval/demo branch is merged.
REPO_BRANCH = "add-evaluation-dataset"

IN_COLAB = False
try:
    import google.colab  # noqa: F401
    IN_COLAB = True
except ImportError:
    pass

if IN_COLAB:
    clone_target = Path("/content") / REPO_NAME
    if not clone_target.exists():
        print(f"Colab detected — cloning {REPO_URL}")
        subprocess.run(["git", "clone", "--depth", "1", "--branch", REPO_BRANCH, REPO_URL, str(clone_target)], check=True)
    os.chdir(clone_target)
    REPO_ROOT = clone_target
else:
    REPO_ROOT = Path.cwd()
    while REPO_ROOT != REPO_ROOT.parent and not (REPO_ROOT / "dataset").exists():
        REPO_ROOT = REPO_ROOT.parent
    if not (REPO_ROOT / "dataset").exists():
        raise RuntimeError(
            f"Could not find repo root (no 'dataset/' dir found walking up from {Path.cwd()})."
        )

SRC_DIR = str(REPO_ROOT / "src")
print(f"Repo root found at: {REPO_ROOT}")
if SRC_DIR not in sys.path:
    sys.path.insert(0, SRC_DIR)

try:
    from dotenv import load_dotenv
    load_dotenv(REPO_ROOT / ".env")
except ImportError:
    print("python-dotenv not installed; relying on shell environment for API keys.")

from eval.sampling import sample_from_dataset
from eval.metrics import grade_mc, cosine_similarity, judge_with_claude, extract_mc_letter

print("Repo root:", REPO_ROOT)
print("Python:", platform.python_version())
print("In Colab:", IN_COLAB)
print("ANTHROPIC_API_KEY loaded:", bool(os.environ.get("ANTHROPIC_API_KEY")))

Repo root found at: /content/COMS6156FinalProject
Repo root: /content/COMS6156FinalProject
Python: 3.12.13
In Colab: True
ANTHROPIC_API_KEY loaded: True

## 2. Build the evaluation set

Set `MODE = "all"` to run every question in every topic file (156 items). Set `MODE = "sample"` to take a stratified N-per-dataset subset for a fast smoke test.

In [2]:
# Build the evaluation set.
#   MODE = "all"     → every question in every topic file across all three datasets
#   MODE = "sample"  → N_PER_DATASET stratified per dataset (fast smoke test)
MODE = "all"
N_PER_DATASET = 5

DATASETS = ["standard_questions", "open_ended_hard", "reddit_questions"]
TOPICS = ["budgeting", "credit_and_debt", "insurance", "investing", "retirement", "tax"]


def load_all_from_dataset(name: str) -> list[dict]:
    base = REPO_ROOT / "dataset" / name
    out = []
    for t in TOPICS:
        items = json.loads((base / f"{t}.json").read_text())
        for it in items:
            out.append({**it, "_dataset": name, "_topic": t})
    return out


items = []
if MODE == "all":
    for ds in DATASETS:
        items.extend(load_all_from_dataset(ds))
else:
    for ds in DATASETS:
        items.extend(sample_from_dataset(ds, N_PER_DATASET, seed=7))

# Per-dataset / per-type counts so you can see what you're about to run
from collections import Counter
by_dataset = Counter(i["_dataset"] for i in items)
by_type = Counter("MC" if i.get("type") == "multiple_choice" else "OE" for i in items)
print(f"MODE={MODE}  total={len(items)}")
print("  by dataset:", dict(by_dataset))
print("  by type:   ", dict(by_type))

MODE=all  total=156
  by dataset: {'standard_questions': 42, 'open_ended_hard': 42, 'reddit_questions': 72}
  by type:    {'OE': 126, 'MC': 30}

## 3. Load the baseline model

Qwen2.5-3B-Instruct runs locally on CPU / Apple Silicon (MPS) / CUDA. First load will download ~6 GB of weights to the HF cache.

In [3]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

MODEL_ID = "Qwen/Qwen2.5-3B-Instruct"

device = (
    "cuda" if torch.cuda.is_available()
    else "mps" if torch.backends.mps.is_available()
    else "cpu"
)
# bfloat16 on MPS avoids fp16-triggered CPU fallbacks that make generation crawl.
# On CUDA, fp16 is fine. On CPU, fp32 is the only option.
if device == "cuda":
    dtype = torch.float16
elif device == "mps":
    dtype = torch.bfloat16
else:
    dtype = torch.float32

# Let unsupported MPS ops fall back to CPU instead of failing (surfaces slow ops instead of hanging).
os.environ.setdefault("PYTORCH_ENABLE_MPS_FALLBACK", "1")

print("Device:", device, "| dtype:", dtype)

t0 = time.time()
tok = AutoTokenizer.from_pretrained(MODEL_ID)
print(f"Tokenizer loaded in {time.time()-t0:.1f}s")

t0 = time.time()
model = AutoModelForCausalLM.from_pretrained(MODEL_ID, dtype=dtype).to(device)
model.eval()
print(f"Model loaded + moved to {device} in {time.time()-t0:.1f}s")

# Warmup: first MPS/CUDA call compiles kernels and is much slower than steady-state.
print("Warming up with a 5-token dummy generation...", flush=True)
t0 = time.time()
_warm = tok("Hello", return_tensors="pt").to(device)
with torch.no_grad():
    model.generate(**_warm, max_new_tokens=5, do_sample=False, pad_token_id=tok.eos_token_id)
print(f"Warmup done in {time.time()-t0:.1f}s")

Device: cuda | dtype: torch.float16

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:103: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Tokenizer loaded in 11.2s

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

Model loaded + moved to cuda in 3.9s
Warming up with a 5-token dummy generation...

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Warmup done in 0.9s

## 4. Prompt templates

For MC items we ask for a single letter so grading is mechanical. For open-ended items we ask for a concise, structured answer.

In [4]:
from transformers import TextStreamer

SYSTEM_PROMPT = (
    "You are a careful personal-finance assistant. "
    "Give direct, accurate, and nuanced answers. "
    "When tradeoffs exist, acknowledge them instead of giving one-sided advice."
)

# Adaptive token budgets: MC items need ~1 letter; OE ~300 is plenty for 4-8 sentences.
MAX_NEW_TOKENS_MC = 10
MAX_NEW_TOKENS_OE = 300


def build_prompt(item: dict) -> list[dict]:
    if item.get("type") == "multiple_choice":
        options = "\n".join(item["options"])
        user = (
            f"{item['question']}\n\n{options}\n\n"
            "Respond with ONLY the single letter (A, B, C, or D) of the best answer."
        )
    else:
        user = (
            f"{item['question']}\n\n"
            "Answer in 4-8 sentences. Be specific and mention tradeoffs where relevant."
        )
    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user},
    ]


def generate(item: dict, max_new_tokens: int | None = None, stream: bool = True, verbose: bool = True) -> str:
    """Generate an answer with optional live token streaming and timing logs."""
    if max_new_tokens is None:
        max_new_tokens = MAX_NEW_TOKENS_MC if item.get("type") == "multiple_choice" else MAX_NEW_TOKENS_OE

    messages = build_prompt(item)

    t_tok = time.time()
    enc = tok.apply_chat_template(
        messages, add_generation_prompt=True, return_tensors="pt", return_dict=True
    )
    input_ids = enc["input_ids"].to(device)
    attention_mask = enc.get("attention_mask")
    if attention_mask is not None:
        attention_mask = attention_mask.to(device)
    prompt_len = input_ids.shape[-1]
    if verbose:
        print(f"    [tokenize] {time.time()-t_tok:.2f}s  prompt_len={prompt_len}  max_new={max_new_tokens}", flush=True)

    streamer = TextStreamer(tok, skip_prompt=True, skip_special_tokens=True) if stream else None

    t_gen = time.time()
    with torch.no_grad():
        out = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tok.eos_token_id,
            streamer=streamer,
        )
    gen_tokens = out.shape[-1] - prompt_len
    dt = time.time() - t_gen
    if verbose:
        tps = gen_tokens / dt if dt > 0 else 0.0
        print(f"\n    [generate] {dt:.2f}s  new_tokens={gen_tokens}  ({tps:.1f} tok/s)", flush=True)

    gen = out[0, prompt_len:]
    return tok.decode(gen, skip_special_tokens=True).strip()

## 5. Run the baseline (resume-safe)

Results are checkpointed to disk after each item, so you can restart the kernel without losing progress — items with an id already in the checkpoint are skipped.

In [5]:
# Run the baseline on all items in `items`. Resume-safe: if RESULTS_PATH already
# exists, previously-completed ids are skipped.
RESULTS_DIR = REPO_ROOT / "src" / "notebooks" / "results"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)
MODEL_SLUG = MODEL_ID.split("/")[-1]
RESULTS_PATH = RESULTS_DIR / f"baseline_{MODEL_SLUG}_all.json"

# Load prior results if present (lets you restart the kernel without losing work).
if RESULTS_PATH.exists():
    results = json.loads(RESULTS_PATH.read_text())
    print(f"Resuming: loaded {len(results)} existing results from {RESULTS_PATH.name}")
else:
    results = []
done_ids = {r["id"] for r in results}

remaining = [it for it in items if it["id"] not in done_ids]
total = len(remaining)
print(f"Running baseline on {total} remaining item(s) of {len(items)} total\n", flush=True)

t_run_start = time.time()
for i, item in enumerate(remaining, 1):
    print(f"[{i}/{total}] {item['_dataset']}/{item['_topic']}/{item['id']}  ({item.get('type', 'open_ended')})", flush=True)
    print(f"  Q: {item['question'][:120]}{'…' if len(item['question']) > 120 else ''}", flush=True)
    t0 = time.time()
    answer = generate(item, stream=False, verbose=True)
    dt = time.time() - t0
    results.append({
        "id": item["id"],
        "dataset": item["_dataset"],
        "topic": item["_topic"],
        "type": item.get("type"),
        "difficulty": item.get("difficulty"),
        "question": item["question"],
        "reference": item["correct_answer"],
        "candidate": answer,
        "latency_sec": round(dt, 2),
    })
    # Checkpoint every item so a crash costs at most one question.
    RESULTS_PATH.write_text(json.dumps(results, indent=2))
    print(f"  → {dt:.1f}s  answer[:100]: {answer[:100]}\n", flush=True)

dt_total = time.time() - t_run_start
print(f"Done. {len(results)}/{len(items)} items. This run: {dt_total:.1f}s "
      f"({dt_total/max(total,1):.1f}s/item).")
print(f"Saved to {RESULTS_PATH}")

Running baseline on 156 remaining item(s) of 156 total

[1/156] standard_questions/budgeting/bud-001  (open_ended)
  Q: What is the 50/30/20 budgeting rule?
    [tokenize] 0.01s  prompt_len=78  max_new=300

    [generate] 5.80s  new_tokens=135  (23.3 tok/s)
  → 5.8s  answer[:100]: The 50/30/20 budgeting rule is a guideline that helps individuals allocate their income into three c

[2/156] standard_questions/budgeting/bud-002  (multiple_choice)
  Q: How many months of expenses should an emergency fund cover?
    [tokenize] 0.00s  prompt_len=118  max_new=10

    [generate] 0.09s  new_tokens=2  (22.5 tok/s)
  → 0.1s  answer[:100]: B

[3/156] standard_questions/budgeting/bud-003  (open_ended)
  Q: What is the difference between a need and a want in the context of budgeting?
    [tokenize] 0.00s  prompt_len=79  max_new=300

    [generate] 6.41s  new_tokens=148  (23.1 tok/s)
  → 6.4s  answer[:100]: In the context of budgeting, distinguishing between needs and wants is crucial for effective financi

[4/156] standard_questions/budgeting/bud-004  (open_ended)
  Q: Should you prioritize paying off high-interest debt or building an emergency fund first?
    [tokenize] 0.00s  prompt_len=77  max_new=300

    [generate] 6.92s  new_tokens=162  (23.4 tok/s)
  → 6.9s  answer[:100]: When deciding between paying off high-interest debt and building an emergency fund, it's important t

[5/156] standard_questions/budgeting/bud-005  (open_ended)
  Q: What is the debt avalanche method vs. the debt snowball method?
    [tokenize] 0.00s  prompt_len=76  max_new=300

    [generate] 9.22s  new_tokens=215  (23.3 tok/s)
  → 9.2s  answer[:100]: The debt avalanche method and the debt snowball method are two popular strategies for paying off deb

[6/156] standard_questions/budgeting/bud-006  (multiple_choice)
  Q: What percentage of your gross income is generally recommended as a maximum for housing costs (rent or mortgage)?
    [tokenize] 0.00s  prompt_len=129  max_new=10

    [generate] 0.10s  new_tokens=2  (19.3 tok/s)
  → 0.1s  answer[:100]: B

[7/156] standard_questions/credit_and_debt/crd-001  (multiple_choice)
  Q: Does checking your own credit score lower it?
    [tokenize] 0.00s  prompt_len=127  max_new=10

    [generate] 0.09s  new_tokens=2  (22.5 tok/s)
  → 0.1s  answer[:100]: B

[8/156] standard_questions/credit_and_debt/crd-002  (multiple_choice)
  Q: How long does a Chapter 7 bankruptcy stay on your credit report?
    [tokenize] 0.00s  prompt_len=121  max_new=10

    [generate] 0.09s  new_tokens=2  (22.6 tok/s)
  → 0.1s  answer[:100]: D

[9/156] standard_questions/credit_and_debt/crd-003  (multiple_choice)
  Q: Which factor has the largest impact on your FICO credit score?
    [tokenize] 0.00s  prompt_len=117  max_new=10

    [generate] 0.09s  new_tokens=2  (22.7 tok/s)
  → 0.1s  answer[:100]: B

[10/156] standard_questions/credit_and_debt/crd-004  (multiple_choice)
  Q: If you only make minimum payments on a $5,000 credit card balance at 22% APR, approximately how long will it take to pay…
    [tokenize] 0.00s  prompt_len=180  max_new=10

    [generate] 0.09s  new_tokens=2  (22.1 tok/s)
  → 0.1s  answer[:100]: C

[11/156] standard_questions/credit_and_debt/crd-005  (multiple_choice)
  Q: Can a debt collector sue you for a debt that is past the statute of limitations?
    [tokenize] 0.00s  prompt_len=159  max_new=10

    [generate] 0.09s  new_tokens=2  (22.4 tok/s)
  → 0.1s  answer[:100]: B

[12/156] standard_questions/credit_and_debt/crd-006  (open_ended)
  Q: What is the difference between a hard inquiry and a soft inquiry on your credit report?
    [tokenize] 0.00s  prompt_len=79  max_new=300

    [generate] 6.87s  new_tokens=159  (23.1 tok/s)
  → 6.9s  answer[:100]: A hard inquiry on your credit report occurs when you apply for new credit or a loan, such as a mortg

[13/156] standard_questions/insurance/ins-001  (open_ended)
  Q: What is the difference between an HMO and a PPO health insurance plan?
    [tokenize] 0.00s  prompt_len=78  max_new=300

    [generate] 8.02s  new_tokens=186  (23.2 tok/s)
  → 8.0s  answer[:100]: An HMO (Health Maintenance Organization) and a PPO (Preferred Provider Organization) are two differe

[14/156] standard_questions/insurance/ins-002  (multiple_choice)
  Q: What is the maximum out-of-pocket limit for an individual marketplace health plan in 2025?
    [tokenize] 0.00s  prompt_len=123  max_new=10

    [generate] 0.09s  new_tokens=2  (22.8 tok/s)
  → 0.1s  answer[:100]: D

[15/156] standard_questions/insurance/ins-003  (open_ended)
  Q: What does term life insurance cover that whole life insurance does not, and vice versa?
    [tokenize] 0.00s  prompt_len=79  max_new=300

    [generate] 6.15s  new_tokens=145  (23.6 tok/s)
  → 6.2s  answer[:100]: Term life insurance primarily covers death benefits for a specified period, typically ranging from 1

[16/156] standard_questions/insurance/ins-004  (multiple_choice)
  Q: Does auto insurance follow the car or the driver?
    [tokenize] 0.00s  prompt_len=149  max_new=10

    [generate] 0.09s  new_tokens=2  (21.5 tok/s)
  → 0.1s  answer[:100]: D

[17/156] standard_questions/insurance/ins-005  (multiple_choice)
  Q: What is the elimination period in a disability insurance policy?
    [tokenize] 0.00s  prompt_len=132  max_new=10

    [generate] 0.09s  new_tokens=2  (22.5 tok/s)
  → 0.1s  answer[:100]: B

[18/156] standard_questions/insurance/ins-006  (multiple_choice)
  Q: Is flood damage covered by a standard homeowner's insurance policy?
    [tokenize] 0.00s  prompt_len=143  max_new=10

    [generate] 0.09s  new_tokens=2  (22.3 tok/s)
  → 0.1s  answer[:100]: B

[19/156] standard_questions/investing/inv-001  (open_ended)
  Q: What is dollar-cost averaging?
    [tokenize] 0.00s  prompt_len=68  max_new=300

    [generate] 6.80s  new_tokens=159  (23.4 tok/s)
  → 6.8s  answer[:100]: Dollar-cost averaging (DCA) is an investment strategy where you invest a fixed amount of money at re

[20/156] standard_questions/investing/inv-002  (multiple_choice)
  Q: When interest rates rise, what generally happens to the price of existing bonds?
    [tokenize] 0.00s  prompt_len=140  max_new=10

    [generate] 0.09s  new_tokens=2  (22.5 tok/s)
  → 0.1s  answer[:100]: B

[21/156] standard_questions/investing/inv-003  (open_ended)
  Q: What is the difference between an ETF and a mutual fund?
    [tokenize] 0.00s  prompt_len=74  max_new=300

    [generate] 7.29s  new_tokens=170  (23.3 tok/s)
  → 7.3s  answer[:100]: Both ETFs (Exchange-Traded Funds) and mutual funds are investment vehicles that pool money from inve

[22/156] standard_questions/investing/inv-004  (multiple_choice)
  Q: What does SIPC (Securities Investor Protection Corporation) protect against?
    [tokenize] 0.00s  prompt_len=123  max_new=10

    [generate] 0.09s  new_tokens=2  (22.7 tok/s)
  → 0.1s  answer[:100]: B

[23/156] standard_questions/investing/inv-005  (multiple_choice)
  Q: Is it possible to lose more money than you invest when buying stocks on margin?
    [tokenize] 0.00s  prompt_len=149  max_new=10

    [generate] 0.09s  new_tokens=2  (22.6 tok/s)
  → 0.1s  answer[:100]: B

[24/156] standard_questions/investing/inv-006  (multiple_choice)
  Q: If an index fund has an expense ratio of 0.03% and another has 1.00%, how much more would the higher-fee fund cost on a …
    [tokenize] 0.00s  prompt_len=177  max_new=10

    [generate] 0.09s  new_tokens=2  (22.2 tok/s)
  → 0.1s  answer[:100]: B

[25/156] standard_questions/investing/inv-007  (open_ended)
  Q: What is a target-date fund and how does its asset allocation change over time?
    [tokenize] 0.00s  prompt_len=78  max_new=300

    [generate] 6.76s  new_tokens=157  (23.2 tok/s)
  → 6.8s  answer[:100]: A target-date fund is a professionally managed investment option that automatically adjusts the asse

[26/156] standard_questions/investing/inv-008  (multiple_choice)
  Q: What is the wash sale rule?
    [tokenize] 0.00s  prompt_len=162  max_new=10

    [generate] 0.09s  new_tokens=2  (22.4 tok/s)
  → 0.1s  answer[:100]: B

[27/156] standard_questions/retirement/ret-001  (multiple_choice)
  Q: What is the maximum 401(k) employee elective deferral limit for 2025 for someone under age 50?
    [tokenize] 0.00s  prompt_len=135  max_new=10

    [generate] 0.09s  new_tokens=2  (22.4 tok/s)
  → 0.1s  answer[:100]: A

[28/156] standard_questions/retirement/ret-002  (multiple_choice)
  Q: Can a 72-year-old with earned income contribute to a Roth IRA?
    [tokenize] 0.00s  prompt_len=146  max_new=10

    [generate] 0.09s  new_tokens=2  (22.4 tok/s)
  → 0.1s  answer[:100]: C

[29/156] standard_questions/retirement/ret-003  (multiple_choice)
  Q: Is there an income limit for contributing to a traditional IRA?
    [tokenize] 0.00s  prompt_len=181  max_new=10

    [generate] 0.09s  new_tokens=2  (22.2 tok/s)
  → 0.1s  answer[:100]: C

[30/156] standard_questions/retirement/ret-004  (multiple_choice)
  Q: At what age must you begin taking Required Minimum Distributions (RMDs) from a traditional 401(k) if you were born in 19…
    [tokenize] 0.00s  prompt_len=127  max_new=10

    [generate] 0.09s  new_tokens=2  (22.7 tok/s)
  → 0.1s  answer[:100]: B

[31/156] standard_questions/retirement/ret-005  (open_ended)
  Q: What is the difference between a traditional IRA and a Roth IRA in terms of tax treatment?
    [tokenize] 0.00s  prompt_len=80  max_new=300

    [generate] 5.00s  new_tokens=117  (23.4 tok/s)
  → 5.0s  answer[:100]: A Traditional IRA allows you to contribute pre-tax income, which can lower your taxable income in th

[32/156] standard_questions/retirement/ret-006  (multiple_choice)
  Q: Can you contribute to both a traditional IRA and a Roth IRA in the same year?
    [tokenize] 0.00s  prompt_len=159  max_new=10

    [generate] 0.09s  new_tokens=2  (22.7 tok/s)
  → 0.1s  answer[:100]: B

[33/156] standard_questions/retirement/ret-007  (multiple_choice)
  Q: What is the Social Security full retirement age for someone born in 1965?
    [tokenize] 0.00s  prompt_len=113  max_new=10

    [generate] 0.09s  new_tokens=2  (22.9 tok/s)
  → 0.1s  answer[:100]: D

[34/156] standard_questions/retirement/ret-008  (multiple_choice)
  Q: If you withdraw money from a traditional IRA before age 59½, what is the early withdrawal penalty?
    [tokenize] 0.00s  prompt_len=135  max_new=10

    [generate] 0.09s  new_tokens=2  (22.7 tok/s)
  → 0.1s  answer[:100]: B

[35/156] standard_questions/tax/tax-001  (multiple_choice)
  Q: Can you deduct student loan interest if you are married filing separately?
    [tokenize] 0.00s  prompt_len=154  max_new=10

    [generate] 0.09s  new_tokens=2  (22.2 tok/s)
  → 0.1s  answer[:100]: C

[36/156] standard_questions/tax/tax-002  (multiple_choice)
  Q: What is the capital gains tax rate for someone in the 32% income tax bracket who sells stock held for 14 months?
    [tokenize] 0.00s  prompt_len=163  max_new=10

    [generate] 0.09s  new_tokens=2  (21.2 tok/s)
  → 0.1s  answer[:100]: B

[37/156] standard_questions/tax/tax-003  (multiple_choice)
  Q: What is the annual gift tax exclusion amount per recipient for 2024?
    [tokenize] 0.00s  prompt_len=123  max_new=10

    [generate] 0.09s  new_tokens=2  (22.6 tok/s)
  → 0.1s  answer[:100]: D

[38/156] standard_questions/tax/tax-004  (multiple_choice)
  Q: Are gifts of money taxable to the recipient?
    [tokenize] 0.00s  prompt_len=151  max_new=10

    [generate] 0.09s  new_tokens=2  (22.3 tok/s)
  → 0.1s  answer[:100]: B

[39/156] standard_questions/tax/tax-005  (multiple_choice)
  Q: What is the standard deduction for a single filer in tax year 2024?
    [tokenize] 0.00s  prompt_len=125  max_new=10

    [generate] 0.09s  new_tokens=2  (22.4 tok/s)
  → 0.1s  answer[:100]: C

[40/156] standard_questions/tax/tax-006  (multiple_choice)
  Q: A freelancer earns $80,000 in net self-employment income. Approximately how much will they owe in self-employment tax (S…
    [tokenize] 0.00s  prompt_len=184  max_new=10

    [generate] 0.09s  new_tokens=2  (22.2 tok/s)
  → 0.1s  answer[:100]: B

[41/156] standard_questions/tax/tax-007  (multiple_choice)
  Q: Can you claim the Earned Income Tax Credit (EITC) if you have no qualifying children?
    [tokenize] 0.00s  prompt_len=145  max_new=10

    [generate] 0.09s  new_tokens=2  (22.5 tok/s)
  → 0.1s  answer[:100]: B

[42/156] standard_questions/tax/tax-008  (open_ended)
  Q: If you work remotely from New York for a company based in California, which state(s) do you owe income tax to?
    [tokenize] 0.00s  prompt_len=87  max_new=300

    [generate] 5.35s  new_tokens=126  (23.6 tok/s)
  → 5.4s  answer[:100]: As a remote worker in New York for a company based in California, you generally owe taxes to both st

[43/156] open_ended_hard/budgeting/bud-007  (open_ended)
  Q: A person takes home $4,800 per month. Their fixed essentials are $2,900, minimum debt payments are $350, and they curren…
    [tokenize] 0.00s  prompt_len=132  max_new=300

    [generate] 10.94s  new_tokens=255  (23.3 tok/s)
  → 10.9s  answer[:100]: Under the 50/30/20 budgeting framework, a person should allocate 50% of their income to needs, 30% t

[44/156] open_ended_hard/budgeting/bud-008  (open_ended)
  Q: If someone gets paid irregularly as a freelancer, is the standard advice of keeping 3-6 months in an emergency fund stil…
    [tokenize] 0.00s  prompt_len=90  max_new=300

    [generate] 5.76s  new_tokens=135  (23.4 tok/s)
  → 5.8s  answer[:100]: For freelancers with irregular pay schedules, maintaining a 3-6 months' worth of living expenses in

[45/156] open_ended_hard/budgeting/bud-009  (open_ended)
  Q: A person has $8,000 in credit card debt at 24% APR and only $500 in savings. They receive a $3,000 bonus. What is a reas…
    [tokenize] 0.00s  prompt_len=117  max_new=300

    [generate] 6.59s  new_tokens=154  (23.4 tok/s)
  → 6.6s  answer[:100]: Given the situation, a reasonable allocation strategy would be to first use part of the bonus to pay

[46/156] open_ended_hard/budgeting/bud-010  (open_ended)
  Q: Why can budgeting based on gross income instead of take-home pay lead to poor spending decisions?
    [tokenize] 0.00s  prompt_len=81  max_new=300

    [generate] 6.97s  new_tokens=163  (23.4 tok/s)
  → 7.0s  answer[:100]: Budgeting based on gross income rather than take-home pay can lead to poor spending decisions becaus

[47/156] open_ended_hard/budgeting/bud-011  (open_ended)
  Q: A household's monthly income is stable, but several large expenses occur only once or twice a year, such as insurance pr…
    [tokenize] 0.00s  prompt_len=115  max_new=300

    [generate] 5.69s  new_tokens=132  (23.2 tok/s)
  → 5.7s  answer[:100]: The household might be making the mistake of not adequately planning for their infrequent but signif

[48/156] open_ended_hard/budgeting/bud-012  (open_ended)
  Q: A person says, 'I had money left over this month, so my budget is working well.' Why might that conclusion be incomplete…
    [tokenize] 0.00s  prompt_len=89  max_new=300

    [generate] 7.17s  new_tokens=167  (23.3 tok/s)
  → 7.2s  answer[:100]: While it's great to have money left over at the end of the month, concluding that your budget is wor

[49/156] open_ended_hard/budgeting/bud-013  (open_ended)
  Q: When inflation raises the cost of groceries, rent, and utilities, should a person interpret a higher 'needs' percentage …
    [tokenize] 0.00s  prompt_len=94  max_new=300

    [generate] 5.11s  new_tokens=119  (23.3 tok/s)
  → 5.1s  answer[:100]: A higher 'needs' percentage in a budget during periods of inflation does not necessarily indicate a

[50/156] open_ended_hard/credit_and_debt/cd-001  (open_ended)
  Q: Why can carrying a balance on a credit card to 'build credit' be bad advice?
    [tokenize] 0.00s  prompt_len=80  max_new=300

    [generate] 5.45s  new_tokens=126  (23.1 tok/s)
  → 5.5s  answer[:100]: Carrying a balance on a credit card primarily to build credit can be considered bad advice because i

[51/156] open_ended_hard/credit_and_debt/cd-002  (open_ended)
  Q: A borrower has two loan options: a 3-year loan with a higher monthly payment and less total interest, or a 6-year loan w…
    [tokenize] 0.00s  prompt_len=110  max_new=300

    [generate] 7.78s  new_tokens=179  (23.0 tok/s)
  → 7.8s  answer[:100]: When deciding between the two loan options, several factors should be considered to determine which

[52/156] open_ended_hard/credit_and_debt/cd-003  (open_ended)
  Q: Why can making only the minimum payment on a high-APR credit card balance be especially costly over time?
    [tokenize] 0.00s  prompt_len=84  max_new=300

    [generate] 6.49s  new_tokens=150  (23.1 tok/s)
  → 6.5s  answer[:100]: Making only the minimum payment on a high-APR credit card can be especially costly over time due to

[53/156] open_ended_hard/credit_and_debt/cd-004  (open_ended)
  Q: A borrower consolidates several credit card balances into a personal loan with a lower interest rate. Why might this sti…
    [tokenize] 0.00s  prompt_len=91  max_new=300

    [generate] 6.78s  new_tokens=157  (23.2 tok/s)
  → 6.8s  answer[:100]: Consolidating multiple credit card balances into a personal loan with a lower interest rate can pote

[54/156] open_ended_hard/credit_and_debt/cd-005  (open_ended)
  Q: If someone closes an old credit card they no longer use, why could that sometimes lower their credit score rather than i…
    [tokenize] 0.00s  prompt_len=87  max_new=300

    [generate] 5.50s  new_tokens=127  (23.1 tok/s)
  → 5.5s  answer[:100]: Closing an old credit card can sometimes lower your credit score because it reduces the average age

[55/156] open_ended_hard/credit_and_debt/cd-006  (open_ended)
  Q: What is the difference between being 'prequalified' for a loan and being actually approved for that loan?
    [tokenize] 0.00s  prompt_len=83  max_new=300

    [generate] 5.95s  new_tokens=138  (23.2 tok/s)
  → 5.9s  answer[:100]: Being prequalified for a loan means a lender has assessed your financial situation based on the info

[56/156] open_ended_hard/credit_and_debt/cd-007  (open_ended)
  Q: Why can a 0% APR promotional credit card offer still be risky for someone trying to get out of debt?
    [tokenize] 0.00s  prompt_len=85  max_new=300

    [generate] 8.64s  new_tokens=200  (23.1 tok/s)
  → 8.6s  answer[:100]: While a 0% APR promotional credit card might seem ideal for consolidating high-interest debts, it co

[57/156] open_ended_hard/insurance/ins-001  (open_ended)
  Q: When choosing between a low-deductible/high-premium health plan and a high-deductible/low-premium plan, what variables s…
    [tokenize] 0.00s  prompt_len=99  max_new=300

    [generate] 7.76s  new_tokens=180  (23.2 tok/s)
  → 7.8s  answer[:100]: When deciding between a low-deductible/high-premium health plan and a high-deductible/low-premium pl

[58/156] open_ended_hard/insurance/ins-002  (open_ended)
  Q: Why can choosing the cheapest possible insurance policy sometimes be financially dangerous even if it lowers monthly cos…
    [tokenize] 0.00s  prompt_len=81  max_new=300

    [generate] 5.26s  new_tokens=122  (23.2 tok/s)
  → 5.3s  answer[:100]: Choosing the cheapest possible insurance policy can sometimes be financially dangerous because these

[59/156] open_ended_hard/insurance/ins-003  (open_ended)
  Q: What is the practical difference between a deductible and an out-of-pocket maximum in health insurance?
    [tokenize] 0.00s  prompt_len=80  max_new=300

    [generate] 6.43s  new_tokens=148  (23.0 tok/s)
  → 6.4s  answer[:100]: A deductible in health insurance is the amount you must pay for covered services out-of-pocket befor

[60/156] open_ended_hard/insurance/ins-004  (open_ended)
  Q: If a healthy person rarely goes to the doctor, does that automatically mean a high-deductible health plan is the best ch…
    [tokenize] 0.00s  prompt_len=88  max_new=300

    [generate] 6.76s  new_tokens=157  (23.2 tok/s)
  → 6.8s  answer[:100]: While a healthy person who rarely visits the doctor might find a high-deductible health plan more af


## 6. Score

### 6a. Multiple-choice accuracy

In [6]:
mc_rows = [r for r in results if r["type"] == "multiple_choice"]
for r in mc_rows:
    g = grade_mc(r["candidate"], r["reference"])
    r["mc_correct"] = g["is_correct"]
    r["mc_picked"] = g["picked"]

if mc_rows:
    correct = sum(1 for r in mc_rows if r["mc_correct"])
    print(f"MC accuracy: {correct}/{len(mc_rows)} = {correct/len(mc_rows):.1%}")
else:
    print("No MC items in this sample.")

MC accuracy: 23/30 = 76.7%

### 6b. Embedding similarity (open-ended)

In [7]:
from sentence_transformers import SentenceTransformer

embedder = SentenceTransformer("BAAI/bge-small-en-v1.5")
oe_rows = [r for r in results if r["type"] != "multiple_choice"]

for r in oe_rows:
    emb_ref, emb_cand = embedder.encode([r["reference"], r["candidate"]], normalize_embeddings=True)
    r["embed_cosine"] = cosine_similarity(emb_ref, emb_cand)

if oe_rows:
    import statistics
    print(f"Mean cosine vs reference: {statistics.mean(r['embed_cosine'] for r in oe_rows):.3f}")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: BAAI/bge-small-en-v1.5
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Mean cosine vs reference: 0.883

### 6c. LLM-as-judge (open-ended)

Requires `ANTHROPIC_API_KEY`. If missing, this cell will be skipped.

In [8]:
if os.environ.get("ANTHROPIC_API_KEY"):
    import anthropic
    judge_client = anthropic.Anthropic()
    for r in oe_rows:
        score = judge_with_claude(
            question=r["question"],
            reference=r["reference"],
            candidate=r["candidate"],
            client=judge_client,
        )
        r["judge"] = score.to_dict()
        print(f"{r['id']:<12}  f={score.factuality} c={score.completeness} a={score.advice_quality}  mean={score.mean:.2f}")
else:
    print("ANTHROPIC_API_KEY not set — skipping LLM judge. Set it and re-run this cell.")

bud-001       f=5 c=4 a=5  mean=4.67
bud-003       f=4 c=4 a=4  mean=4.00
bud-004       f=2 c=2 a=3  mean=2.33
bud-005       f=5 c=5 a=5  mean=5.00
crd-006       f=4 c=4 a=4  mean=4.00
ins-001       f=4 c=4 a=4  mean=4.00
ins-003       f=5 c=4 a=5  mean=4.67
inv-001       f=5 c=5 a=5  mean=5.00
inv-003       f=3 c=3 a=3  mean=3.00
inv-007       f=5 c=4 a=4  mean=4.33
ret-005       f=4 c=5 a=4  mean=4.33
tax-008       f=2 c=2 a=2  mean=2.00
bud-007       f=4 c=4 a=4  mean=4.00
bud-008       f=2 c=2 a=3  mean=2.33
bud-009       f=2 c=2 a=2  mean=2.00
bud-010       f=5 c=5 a=5  mean=5.00
bud-011       f=5 c=4 a=5  mean=4.67
bud-012       f=3 c=3 a=4  mean=3.33
bud-013       f=5 c=5 a=5  mean=5.00
cd-001        f=4 c=4 a=5  mean=4.33
cd-002        f=4 c=4 a=4  mean=4.00
cd-003        f=5 c=5 a=4  mean=4.67
cd-004        f=4 c=4 a=4  mean=4.00
cd-005        f=4 c=5 a=5  mean=4.67
cd-006        f=4 c=4 a=4  mean=4.00
cd-007        f=4 c=3 a=4  mean=3.67
ins-001       f=4 c=3 a=4  mean=3.67
ins-002       f=4 c=4 a=4  mean=4.00
ins-003       f=4 c=4 a=4  mean=4.00
ins-004       f=3 c=3 a=3  mean=3.00
ins-005       f=3 c=5 a=5  mean=4.33
ins-006       f=5 c=5 a=4  mean=4.67
ins-007       f=3 c=3 a=3  mean=3.00
inv-001       f=5 c=5 a=5  mean=5.00
inv-002       f=4 c=3 a=3  mean=3.33
inv-003       f=4 c=4 a=4  mean=4.00
inv-004       f=4 c=4 a=4  mean=4.00
inv-005       f=3 c=4 a=4  mean=3.67
inv-006       f=4 c=4 a=4  mean=4.00
inv-007       f=5 c=5 a=5  mean=5.00
ret-001       f=3 c=3 a=3  mean=3.00
ret-002       f=2 c=2 a=2  mean=2.00
ret-003       f=2 c=3 a=3  mean=2.67
ret-004       f=5 c=5 a=5  mean=5.00
ret-005       f=4 c=4 a=4  mean=4.00
ret-006       f=4 c=4 a=4  mean=4.00
ret-007       f=3 c=4 a=4  mean=3.67
tax-001       f=4 c=4 a=4  mean=4.00
tax-002       f=4 c=5 a=4  mean=4.33
tax-003       f=4 c=4 a=4  mean=4.00
tax-004       f=2 c=2 a=2  mean=2.00
tax-005       f=3 c=4 a=3  mean=3.33
tax-006       f=3 c=3 a=3  mean=3.00
tax-007       f=4 c=3 a=4  mean=3.67
bud-r-001     f=3 c=2 a=2  mean=2.33
bud-r-002     f=2 c=3 a=3  mean=2.67
bud-r-003     f=3 c=3 a=3  mean=3.00
bud-r-004     f=3 c=2 a=3  mean=2.67
bud-r-005     f=3 c=2 a=2  mean=2.33
bud-r-006     f=2 c=3 a=3  mean=2.67
bud-r-007     f=3 c=2 a=3  mean=2.67
bud-r-008     f=2 c=2 a=2  mean=2.00
bud-r-009     f=3 c=3 a=3  mean=3.00
bud-r-010     f=2 c=2 a=2  mean=2.00
bud-r-011     f=3 c=2 a=2  mean=2.33
bud-r-012     f=3 c=2 a=2  mean=2.33
cd-r-001      f=2 c=2 a=2  mean=2.00
cd-r-002      f=3 c=3 a=3  mean=3.00
cd-r-003      f=3 c=2 a=3  mean=2.67
cd-r-004      f=4 c=3 a=4  mean=3.67
cd-r-005      f=3 c=2 a=3  mean=2.67
cd-r-006      f=3 c=2 a=2  mean=2.33
cd-r-007      f=3 c=2 a=2  mean=2.33
cd-r-008      f=3 c=3 a=3  mean=3.00
cd-r-009      f=3 c=2 a=3  mean=2.67
cd-r-010      f=3 c=2 a=3  mean=2.67
cd-r-011      f=2 c=3 a=2  mean=2.33
cd-r-012      f=2 c=2 a=2  mean=2.00
ins-r-001     f=3 c=2 a=3  mean=2.67
ins-r-002     f=3 c=2 a=2  mean=2.33
ins-r-003     f=3 c=2 a=3  mean=2.67
ins-r-004     f=2 c=2 a=2  mean=2.00
ins-r-005     f=2 c=2 a=2  mean=2.00
ins-r-006     f=2 c=1 a=2  mean=1.67
ins-r-007     f=2 c=2 a=2  mean=2.00
ins-r-008     f=3 c=3 a=3  mean=3.00
ins-r-009     f=2 c=2 a=2  mean=2.00
ins-r-010     f=1 c=2 a=2  mean=1.67
ins-r-011     f=2 c=2 a=2  mean=2.00
ins-r-012     f=3 c=2 a=3  mean=2.67
inv-r-001     f=4 c=2 a=3  mean=3.00
inv-r-002     f=2 c=2 a=2  mean=2.00
inv-r-003     f=3 c=3 a=3  mean=3.00
inv-r-004     f=3 c=2 a=2  mean=2.33
inv-r-005     f=3 c=2 a=3  mean=2.67
inv-r-006     f=3 c=2 a=3  mean=2.67
inv-r-007     f=2 c=2 a=2  mean=2.00
inv-r-008     f=3 c=2 a=3  mean=2.67
inv-r-009     f=3 c=3 a=3  mean=3.00
inv-r-010     f=2 c=3 a=3  mean=2.67
inv-r-011     f=2 c=2 a=2  mean=2.00
inv-r-012     f=2 c=2 a=2  mean=2.00
ret-r-001     f=2 c=2 a=2  mean=2.00
ret-r-002     f=2 c=2 a=2  mean=2.00
ret-r-003     f=2 c=2 a=2  mean=2.00
ret-r-004     f=2 c=2 a=2  mean=2.00
ret-r-005     f=3 c=3 a=3  mean=3.00
ret-r-006     f=3 c=3 a=3  mean=3.00
ret-r-007     f=2 c=3 a=3  mean=2.67
ret-r-008     f=3 c=2 a=2  mean=2.33
ret-r-009     f=2 c=2 a=2  mean=2.00
ret-r-010     f=2 c=2 a=2  mean=2.00
ret-r-011     f=2 c=3 a=2  mean=2.33
ret-r-012     f=2 c=2 a=2  mean=2.00
tax-r-001     f=1 c=1 a=1  mean=1.00
tax-r-002     f=2 c=2 a=2  mean=2.00
tax-r-003     f=2 c=3 a=2  mean=2.33
tax-r-004     f=3 c=3 a=3  mean=3.00
tax-r-005     f=2 c=2 a=2  mean=2.00
tax-r-006     f=4 c=3 a=3  mean=3.33
tax-r-007     f=2 c=2 a=2  mean=2.00
tax-r-008     f=2 c=2 a=2  mean=2.00
tax-r-009     f=1 c=2 a=2  mean=1.67
tax-r-010     f=2 c=2 a=2  mean=2.00
tax-r-011     f=2 c=2 a=2  mean=2.00
tax-r-012     f=1 c=1 a=1  mean=1.00

## 7. Summary tables

In [9]:
import pandas as pd
df = pd.DataFrame(results)
df.head()

,id,dataset,topic,type,difficulty,question,reference,candidate,latency_sec,embed_cosine,judge,mc_correct,mc_picked
0,bud-001,standard_questions,budgeting,open_ended,basic,What is the 50/30/20 budgeting rule?,The 50/30/20 rule suggests allocating your aft...,The 50/30/20 budgeting rule is a guideline tha...,5.81,0.862503,"{'factuality': 5, 'completeness': 4, 'advice_q...",NaN,NaN
1,bud-002,standard_questions,budgeting,multiple_choice,basic,How many months of expenses should an emergenc...,B,B,0.09,NaN,NaN,True,B
2,bud-003,standard_questions,budgeting,open_ended,basic,What is the difference between a need and a wa...,A need is an essential expense required for ba...,"In the context of budgeting, distinguishing be...",6.42,0.889655,"{'factuality': 4, 'completeness': 4, 'advice_q...",NaN,NaN
3,bud-004,standard_questions,budgeting,open_ended,intermediate,Should you prioritize paying off high-interest...,Most financial advisors recommend a balanced a...,When deciding between paying off high-interest...,6.93,0.873562,"{'factuality': 2, 'completeness': 2, 'advice_q...",NaN,NaN
4,bud-005,standard_questions,budgeting,open_ended,intermediate,What is the debt avalanche method vs. the debt...,The debt avalanche method prioritizes paying o...,The debt avalanche method and the debt snowbal...,9.23,0.963314,"{'factuality': 5, 'completeness': 5, 'advice_q...",NaN,NaN

In [10]:
# Per-dataset aggregates
def agg(g):
    row = {"n": len(g)}
    if "mc_correct" in g.columns:
        mc = g.dropna(subset=["mc_correct"])
        row["mc_accuracy"] = mc["mc_correct"].mean() if len(mc) else None
    if "embed_cosine" in g.columns:
        row["mean_cosine"] = g["embed_cosine"].mean()
    if "judge" in g.columns:
        judged = g.dropna(subset=["judge"])
        if len(judged):
            row["judge_factuality"] = judged["judge"].apply(lambda j: j["factuality"]).mean()
            row["judge_completeness"] = judged["judge"].apply(lambda j: j["completeness"]).mean()
            row["judge_advice"] = judged["judge"].apply(lambda j: j["advice_quality"]).mean()
            row["judge_mean"] = judged["judge"].apply(lambda j: j["mean"]).mean()
    row["mean_latency_sec"] = g["latency_sec"].mean()
    return pd.Series(row)

df.groupby("dataset").apply(agg)

/tmp/ipykernel_16344/3208443437.py:19: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby("dataset").apply(agg)

,n,mc_accuracy,mean_cosine,judge_factuality,judge_completeness,judge_advice,judge_mean,mean_latency_sec
dataset,,,,,,,,
open_ended_hard,42.0,NaN,0.893431,3.738095,3.809524,3.880952,3.809524,6.765476
reddit_questions,72.0,NaN,0.870248,2.458333,2.222222,2.388889,2.356481,7.292917
standard_questions,42.0,0.766667,0.922362,4.000000,3.833333,4.000000,3.944444,1.985238

## 8. Persist results (sharded by dataset / topic / type)

Writes the full `results` list plus per-dataset, per-(dataset, topic), and per-type JSON files under `src/notebooks/results/baseline_<model>/`.

In [11]:
# Shard results by dataset and by (dataset, topic) so they're easy to inspect
# and to diff against the RAG results later. Also write a CSV summary.
from collections import defaultdict

OUT_DIR = REPO_ROOT / "src" / "notebooks" / "results" / f"baseline_{MODEL_SLUG}"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Combined file (same content as checkpoint above)
(OUT_DIR / "all.json").write_text(json.dumps(results, indent=2))

# Per-dataset
by_dataset: dict[str, list[dict]] = defaultdict(list)
for r in results:
    by_dataset[r["dataset"]].append(r)
for ds, rows in by_dataset.items():
    (OUT_DIR / f"{ds}.json").write_text(json.dumps(rows, indent=2))

# Per-dataset/topic
by_dt: dict[tuple[str, str], list[dict]] = defaultdict(list)
for r in results:
    by_dt[(r["dataset"], r["topic"])].append(r)
topic_dir = OUT_DIR / "by_topic"
topic_dir.mkdir(exist_ok=True)
for (ds, tp), rows in by_dt.items():
    (topic_dir / f"{ds}__{tp}.json").write_text(json.dumps(rows, indent=2))

# Per-type (MC vs OE) — handy for computing accuracy on MC only
by_type: dict[str, list[dict]] = defaultdict(list)
for r in results:
    key = "multiple_choice" if r.get("type") == "multiple_choice" else "open_ended"
    by_type[key].append(r)
for k, rows in by_type.items():
    (OUT_DIR / f"type_{k}.json").write_text(json.dumps(rows, indent=2))

print(f"Wrote {len(results)} results to {OUT_DIR}")
print(f"  datasets: {sorted(by_dataset)}")
print(f"  topic shards: {len(by_dt)}")
print(f"  types: {sorted(by_type)}")

Wrote 156 results to /content/COMS6156FinalProject/src/notebooks/results/baseline_Qwen2.5-3B-Instruct
  datasets: ['open_ended_hard', 'reddit_questions', 'standard_questions']
  topic shards: 18
  types: ['multiple_choice', 'open_ended']

## 9. (Optional) Claude-without-RAG second baseline

This isolates the contribution of retrieval. Uncomment to run once you're happy with the Qwen results.

In [ ]:
# if os.environ.get("ANTHROPIC_API_KEY"):
#     import anthropic
#     client = anthropic.Anthropic()
#     CLAUDE_MODEL = "claude-sonnet-4-6"
#     claude_results = []
#     for item in sampled:
#         msgs = build_prompt(item)
#         resp = client.messages.create(
#             model=CLAUDE_MODEL, max_tokens=600,
#             system=msgs[0]["content"],
#             messages=[{"role": "user", "content": msgs[1]["content"]}],
#         )
#         claude_results.append({
#             "id": item["id"], "dataset": item["_dataset"], "topic": item["_topic"],
#             "type": item.get("type"), "question": item["question"],
#             "reference": item["correct_answer"], "candidate": resp.content[0].text.strip(),
#         })
#     (OUT_DIR / f"baseline_{CLAUDE_MODEL}_no_rag.json").write_text(json.dumps(claude_results, indent=2))
#     print("Saved Claude no-RAG baseline.")